CREATE FUNCTION TotalPointOfCustomer(id INT)
    RETURNS INT
    READS SQL DATA
    DETERMINISTIC
BEGIN
    DECLARE point INT;

    SELECT CUS_TOTAL_POINT INTO point
    FROM CUSTOMER
    WHERE CUS_ID = id;

    RETURN point;
END;

CREATE TRIGGER IDofCustomer
BEFORE INSERT
ON customer
Begin
    INSERT INTO Customer (CUS_ID, CUS_NAME, CUS_ADDRESS, CUS_PHONE_NUMBER,
    IF NEW.Customer.ID IS NULL THEN
        UPDATE Customer
        SET CUS_ID = (SELECT MAX(CUS_ID) FROM Customer) + 1
        WHERE CUS_ID = NEW::Customer.ID;
    END IF;
END
